const stage=document.querySelector('#stage'),gt=document.querySelector('#gt'),gc=document.querySelector('#gc'),meaning=document.querySelector('#meaning'),step=document.querySelector('#step'),prompt=document.querySelector('.storyPrompt');
const memories=[
{title:'The token plant',copy:'Adding a marginalized voice is not enough if the classroom around it remains unchanged.',meaning:'Representation has been added, but the system supporting it has not changed.',sel:'.plantObj',anim:'wilt'},
{title:'The new text',copy:'A new author can enter the syllabus while old habits still control how that work is taught.',meaning:'The book changes. The surrounding structure does not.',sel:'.morrisonObj',anim:'bookmove'},
{title:'The syllabus',copy:'Transformation asks us to reconsider the structure, not simply append new material.',meaning:'The reading list is visible change; pedagogy is the deeper change.',sel:'.syllabusObj',anim:'camera'},
{title:'The podium',copy:'Who holds authority in the room matters alongside what appears on the reading list.',meaning:'The oversized podium makes unchanged classroom authority physically loom over the scene.',sel:'.podiumObj',anim:'loom'},
{title:'Good intentions',copy:'Good intentions can begin the work, but they do not complete transformation.',meaning:'Intention is not the same thing as structural change.',sel:'.mugObj',anim:'message'}];
const visited=new Set();let current=-1,tour=localStorage.getItem('hooksTourComplete')!=='1';
function clear(){document.querySelector('.plantObj')?.classList.remove('vector-wilt');document.querySelectorAll('.object').forEach(o=>o.classList.remove('active','dim','animate'));stage.classList.remove('focusMode');document.body.dataset.anim=''}
function activate(i,fromTour=false){current=i;const m=memories[i];clear();visited.add(i);gt.textContent=m.title;gc.textContent=m.copy;meaning.textContent=m.meaning;step.textContent=String(i+1).padStart(2,'0')+' / 05';const obj=document.querySelector(m.sel);document.querySelectorAll('.object').forEach(o=>o.classList.add('dim'));obj.classList.remove('dim');obj.classList.add('active','animate');if(i===0){requestAnimationFrame(()=>obj.classList.add('vector-wilt'))}stage.classList.add('focusMode');document.body.dataset.anim=m.anim;document.querySelectorAll('.hot').forEach((h,j)=>{h.classList.toggle('visited',visited.has(j));h.classList.toggle('hiddenCue',j!==i)});prompt.style.display='none';document.querySelector('footer b').textContent=`${visited.size} of 5 memories discovered`;document.querySelector('.dots').textContent=[0,1,2,3,4].map(j=>visited.has(j)?'●':'○').join(' ');if(tour){const next=i<4?i+1:-1;setTimeout(()=>{if(current!==i)return;if(next>=0){prompt.style.display='block';prompt.innerHTML=`Next: ${memories[next].title} <span>→</span>`;prompt.onclick=()=>activate(next,true)}else{localStorage.setItem('hooksTourComplete','1');tour=false;prompt.style.display='block';prompt.innerHTML='Tour complete · explore freely';setTimeout(()=>prompt.style.display='none',2500)}},1200)}}
document.querySelectorAll('[data-i]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();activate(+el.dataset.i)}));
document.querySelector('#reset').addEventListener('click',()=>{clear();gt.textContent='Look around the room.';gc.textContent=tour?'Start with the wilted plant. The room will guide you through the argument.':'Explore freely. Each object is now a retrieval cue.';meaning.textContent='Select an object to reveal what it represents.';step.textContent='—';prompt.style.display='block';prompt.innerHTML=tour?'Start with the plant <span>→</span>':'Choose any memory object';prompt.onclick=tour?()=>activate(0,true):null});
stage.addEventListener('pointermove',e=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches||stage.classList.contains('focusMode'))return;const r=stage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;document.querySelector('.bg').style.transform=`translate(${x*-8}px,${y*-5}px) scale(1.03)`;document.querySelector('.rays').style.marginLeft=`${x*-12}px`;document.querySelectorAll('.object').forEach((el,i)=>el.style.translate=`${x*(5+i*2)}px ${y*(3+i)}px`)});
if(tour){prompt.onclick=()=>activate(0,true)}else{prompt.textContent='Choose any memory object'}